language: objective-c
osx_image: xcode7.3

before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- cd Project-iOS/XLProjectName && pod repo update && pod install

script:
- xctool clean build -workspace XLProjectName.xcworkspace -scheme XLProjectName -sdk iphonesimulator | xcpretty
- xcodebuild test -workspace XLProjectName.xcworkspace -scheme XLProjectName -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=9.3' | xcpretty
